# Generated by Django 3.0.5 on 2020-05-14 22:44

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('egresados', '__first__'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('contenido', ckeditor.fields.RichTextField(verbose_name='Descripcion')),
                ('imagen', models.URLField(max_length=100, verbose_name='Imagen de Fondo')),
                ('fechaCreacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('egresados', models.ManyToManyField(to='egresados.Egresado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.EmpresaUsuario')),
            ],
        ),
    ]
